### PR TITLE
Issue #943: Add first pass of time-entry documentation

### PR DESCRIPTION
**Pull request by chrisarusso**

### CODE REVIEW

**Comment by kostajh** [comment]
@chrisarusso what do you think about adding 1-2 made up examples of good time entries and 1-2 bad ones?

**Comment by chrisarusso** [comment]
Maybe we can have an examples section, or the like @kostajh ? I'm in favor of keeping the instructions as succinct as possible so that people will actually read them. Open to discussion on it for sure.

**Comment by kostajh** [comment]
@chrisarusso For me, a concrete example is usually what I look for when trying to understand how I should do something, and I tend to ignore the surrounding words :joy_cat:  so I'd like to have one. I can add it if you like.

**Comment by kostajh** [comment]
Also wanted to add — my preference is to have examples within the context of the page that they relate to, rather than on their own "Examples" page.

**Comment by kostajh** [comment]
@chrisarusso over to you, I think it's ready to merge!

**Pull request merged**
