### PR TITLE
[WIP] Issue #936: customize theme

### PR DESCRIPTION
**Pull request by AnneTee**
@kostajh I wrote a bunch of shameful CSS to override the theme with our colors and fonts. I'm sure other items will come up that could use customization, but this will get us started.

### CODE REVIEW

**Comment by kostajh** [comment]
Looking good! A few suggestions:

**Comment by kostajh** [comment]
Looking good! A few suggestions:

- [ ] Code block font could be a few points bigger, IMO, e.g. the blocks on README.html#building-the-project-locally
- [ ] Should we load a nicer font from Google?
- [ ] Visited links are hard to read
- [ ] Inline `<code>` elements are hard to read, again probably due to font size. Maybe the global font size could be bumped up a bit? 
- [ ] A more distinctive style between H1, H2 and H3 would help with readability, currently the only difference is in size. Background color, underline, different color, etc

**Comment by chrisarusso** [comment]
I think it looks great and much more Savasian @AnneTee :+1: 

I would add to @kostajh 's checklist is: 
- [ ] Add a style for a blockquote. The numbered list here: http://127.0.0.1:8000/git.html#git-commit-messages is in blockquotes, but you can't tell.

**Comment by AnneTee** [comment]
@kostajh and @chrisarusso I made some adjustments to heading and blockquote styles, and bumped up the font size.

For some reason, I can't get Roboto Condensed to load. Roboto and PT Serif both work fine.

I'd like to update our fonts on the website in the near future anyway, so I'll update text styles here to match when that happens. Let me know if you have any other adjustments we can make now! 🐝

**Comment by chrisarusso** [comment]
I'm in favor of merging and improving over time :+1: 

Thanks @AnneTee !

**Pull request merged**
